//! Creating a site's main Worker on its first `impresspress deploy`.
//!
//! Every deploy ships the main Worker with `wrangler versions upload`, which
//! cannot create a Worker: for a script name the account does not have,
//! Cloudflare answers error 10007. The deploy's `/_deploy/*` endpoints also
//! need two secrets on the Worker (`IMPRESSPRESS_DEPLOY_TOKEN` and the auth
//! JWT secret) before its candidate can be prepared, and a secret can only be
//! set on a Worker that exists.
//!
//! So `impresspress deploy` asks Cloudflare whether the main Worker exists
//! before it builds anything ([`plan_main_worker`]). When it does, the deploy
//! needs the operator's `IMPRESSPRESS_DEPLOY_TOKEN` and nothing else changes.
//! When it does not, the deploy creates it ([`create_main_worker`]) once the
//! password-hasher Worker is deployed: a plain `wrangler deploy` of a
//! placeholder that answers every request with a 503, never the application
//! (nothing is migrated yet, and the placeholder binds nothing), then the two
//! secrets. From there the ordinary funnel runs — candidate upload,
//! `/_deploy/prepare`, the verified final version, promotion — and promotion
//! replaces the placeholder.
//!
//! The wrangler calls sit behind [`WorkerCommands`] so the decisions here are
//! tested without a Cloudflare account; [`Wrangler`] is the implementation
//! the CLI runs.

use std::{
    ffi::OsString,
    io::Write,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use anyhow::{bail, Context, Result};

use super::wrangler::CloudflareConfig;

/// Where the placeholder's config and module are written, relative to the
/// consumer's repository root. Not under `target/impresspress-cloudflare`,
/// which `impresspress build` empties: the existence check runs before the
/// build.
pub const FIRST_CREATE_DIR: &str = "target/impresspress-cloudflare-first-create";

/// The placeholder's entry module, next to its config.
pub const PLACEHOLDER_MODULE: &str = "placeholder.mjs";

/// How wrangler renders Cloudflare's "this Worker does not exist on your
/// account" API error (`isWorkerNotFoundError` in wrangler's source matches
/// the same code).
const WORKER_NOT_FOUND: &str = "[code: 10007]";

/// The placeholder Worker's code: a 503 for every request until the first
/// prepared version is promoted over it.
const PLACEHOLDER_SOURCE: &str =
    "// Generated by `impresspress deploy`: stands in for this Worker until the \
first prepared version of the site is promoted over it.\n\
export default {\n  \
async fetch() {\n    \
return new Response(\"This site is being deployed.\\n\", {\n      \
status: 503,\n      \
headers: { \"Content-Type\": \"text/plain; charset=utf-8\", \"Retry-After\": \"60\" },\n    \
});\n  \
},\n\
};\n";

/// The wrangler commands creating a Worker needs.
pub trait WorkerCommands {
    /// Whether the Worker `config` names exists on its account. `Err` for any
    /// failure other than Cloudflare's "does not exist" answer: an
    /// authentication or network failure must not read as an absent Worker,
    /// or the deploy would deploy a placeholder over a live site.
    fn worker_exists(&self, config: &Path) -> Result<bool>;
    /// `wrangler deploy` of `config`, which creates the Worker when absent.
    fn deploy(&self, config: &Path) -> Result<()>;
    /// Set secret `name` on `config`'s Worker.
    fn secret_put(&self, config: &Path, name: &str, value: &str) -> Result<()>;
    /// The NAMES of the secrets `config`'s Worker holds; never a value.
    fn secret_names(&self, config: &Path) -> Result<Vec<String>>;
}

/// [`WorkerCommands`] through the `wrangler` CLI.
pub struct Wrangler {
    program: OsString,
}

impl Default for Wrangler {
    fn default() -> Self {
        Self::at("wrangler")
    }
}

impl Wrangler {
    /// Run `program` as wrangler. The CLI uses [`Wrangler::default`]; a test
    /// points this at a script that answers the way wrangler does.
    pub fn at(program: impl Into<OsString>) -> Self {
        Self {
            program: program.into(),
        }
    }
}

impl WorkerCommands for Wrangler {
    fn worker_exists(&self, config: &Path) -> Result<bool> {
        let output = Command::new(&self.program)
            .args(["deployments", "status", "--json", "--config"])
            .arg(config)
            .output()
            .context("run wrangler deployments status")?;
        if output.status.success() {
            return Ok(true);
        }
        let diagnostics = format!(
            "{}\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        if diagnostics.contains(WORKER_NOT_FOUND) {
            return Ok(false);
        }
        bail!(
            "wrangler deployments status --config {} failed (exit {:?}), so whether the Worker \
             exists is unknown: {}",
            config.display(),
            output.status.code(),
            diagnostics.trim()
        )
    }

    fn deploy(&self, config: &Path) -> Result<()> {
        let status = Command::new(&self.program)
            .args(["deploy", "--config"])
            .arg(config)
            .status()
            .context("run wrangler deploy")?;
        if !status.success() {
            bail!(
                "wrangler deploy --config {} failed (exit {:?})",
                config.display(),
                status.code()
            );
        }
        Ok(())
    }

    /// The value goes to wrangler on stdin, never as an argument, which would
    /// put it in the process table.
    fn secret_put(&self, config: &Path, name: &str, value: &str) -> Result<()> {
        let mut child = Command::new(&self.program)
            .args(["secret", "put", name, "--config"])
            .arg(config)
            .stdin(Stdio::piped())
            .spawn()
            .context("spawn wrangler secret put")?;
        child
            .stdin
            .take()
            .context("wrangler secret put stdin unavailable")?
            .write_all(value.as_bytes())
            .context("write secret value to wrangler stdin")?;
        let status = child.wait().context("wait for wrangler secret put")?;
        if !status.success() {
            bail!(
                "wrangler secret put {name} failed (exit {:?})",
                status.code()
            );
        }
        Ok(())
    }

    fn secret_names(&self, config: &Path) -> Result<Vec<String>> {
        let output = Command::new(&self.program)
            .args(["secret", "list", "--format", "json", "--config"])
            .arg(config)
            .output()
            .context("run wrangler secret list")?;
        if !output.status.success() {
            bail!(
                "wrangler secret list --config {} failed (exit {:?}): {}",
                config.display(),
                output.status.code(),
                String::from_utf8_lossy(&output.stderr).trim()
            );
        }
        super::password_hasher::parse_secret_names(&String::from_utf8_lossy(&output.stdout))
    }
}

/// Write the placeholder Worker's config and module into `dir`, returning
/// the config's path. The config names the main Worker and its account and
/// nothing the application needs: no bindings, no vars, no routes. Preview
/// URLs are on, as in every generated main-Worker config, because the
/// candidate upload that follows reads its preview URL.
pub fn generate_placeholder(cfg: &CloudflareConfig, dir: &Path) -> Result<PathBuf> {
    use toml::Value;

    std::fs::create_dir_all(dir).with_context(|| format!("create {}", dir.display()))?;
    let mut root = toml::map::Map::new();
    root.insert("name".into(), Value::String(cfg.worker_name.clone()));
    root.insert("account_id".into(), Value::String(cfg.account_id.clone()));
    root.insert("main".into(), Value::String(PLACEHOLDER_MODULE.into()));
    root.insert(
        "compatibility_date".into(),
        Value::String(cfg.compatibility_date.clone()),
    );
    root.insert("preview_urls".into(), Value::Boolean(true));
    let body =
        toml::to_string_pretty(&Value::Table(root)).context("serialize placeholder config")?;

    std::fs::write(dir.join(PLACEHOLDER_MODULE), PLACEHOLDER_SOURCE)
        .with_context(|| format!("write {}", dir.join(PLACEHOLDER_MODULE).display()))?;
    let path = dir.join("wrangler.toml");
    std::fs::write(
        &path,
        format!(
            "# Generated by `impresspress deploy`: creates the Worker on a site's first deploy, \
             serving a 503 until the first prepared version is promoted. Do not edit.\n\n{body}"
        ),
    )
    .with_context(|| format!("write {}", path.display()))?;
    Ok(path)
}

/// What this deploy does about the main Worker, decided before the build.
#[derive(Debug, PartialEq, Eq)]
pub enum MainWorkerPlan {
    /// The Worker exists; the deploy authenticates with this token.
    Existing { deploy_token: String },
    /// The account has no Worker by this name: [`create_main_worker`] makes
    /// it after the password-hasher deploy.
    Create,
}

/// Ask Cloudflare whether `worker_name` (the Worker `placeholder_config`
/// names) exists, and decide what this deploy needs.
///
/// An existing Worker is first given any of `secrets` it does not hold (by
/// name; no value is read), so a first deploy that stopped after creating the
/// Worker but before setting both secrets is finished by the next run rather
/// than left without a JWT secret. Then it needs the token its `/_deploy/*`
/// endpoints were given: the one just set, or `deploy_token`, without which
/// this refuses, naming the one command that sets a new one. An absent Worker
/// needs no token yet; [`create_main_worker`] sets `secrets`.
pub fn plan_main_worker(
    commands: &impl WorkerCommands,
    placeholder_config: &Path,
    worker_name: &str,
    secrets: &[WorkerSecret],
    deploy_token: Option<String>,
) -> Result<MainWorkerPlan> {
    let token_key = impresspress_core::config_vars::DEPLOY_TOKEN_KEY;
    if !commands.worker_exists(placeholder_config)? {
        return Ok(MainWorkerPlan::Create);
    }
    let held = commands.secret_names(placeholder_config)?;
    let missing: Vec<WorkerSecret> = secrets
        .iter()
        .filter(|secret| !held.iter().any(|name| name == secret.name))
        .cloned()
        .collect();
    put_worker_secrets(commands, placeholder_config, &missing)?;
    if let Some(set) = missing.iter().find(|secret| secret.name == token_key) {
        return Ok(MainWorkerPlan::Existing {
            deploy_token: set.value.clone(),
        });
    }
    match deploy_token.filter(|token| !token.is_empty()) {
        Some(deploy_token) => Ok(MainWorkerPlan::Existing { deploy_token }),
        None => bail!(
            "{token_key} is not set. The Worker {worker_name} exists, so this deploy needs the \
             token its /_deploy endpoints were given: export {token_key}=<that value>. If it is \
             lost, set a new one on the Worker and export the same value: \
             npx wrangler secret put {token_key} --name {worker_name}"
        ),
    }
}

/// One secret a newly created Worker is given.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkerSecret {
    pub name: &'static str,
    pub value: String,
    /// Minted here rather than taken from the same-named environment variable.
    pub generated: bool,
}

/// The secrets a Worker's deploy funnel needs — `IMPRESSPRESS_DEPLOY_TOKEN`
/// and the auth JWT secret — each from the same-named environment variable
/// when `from_env` has a non-empty one, otherwise minted from 32 bytes of
/// `random`.
pub fn resolve_worker_secrets(
    from_env: impl Fn(&str) -> Option<String>,
    mut random: impl FnMut() -> Result<[u8; 32]>,
) -> Result<Vec<WorkerSecret>> {
    [
        impresspress_core::config_vars::DEPLOY_TOKEN_KEY,
        impresspress_core::blocks::auth::JWT_SECRET_KEY,
    ]
    .into_iter()
    .map(|name| {
        let (value, generated) = super::deploy::resolve_secret(from_env(name), &random()?);
        Ok(WorkerSecret {
            name,
            value,
            generated,
        })
    })
    .collect()
}

/// Put `secrets` on `config`'s Worker, in order, reporting each as soon as
/// it is set: a generated deploy token is printed the moment the Worker holds
/// it, so a later failure cannot lose the only copy.
pub fn put_worker_secrets(
    commands: &impl WorkerCommands,
    config: &Path,
    secrets: &[WorkerSecret],
) -> Result<()> {
    for secret in secrets {
        commands.secret_put(config, secret.name, &secret.value)?;
        report_worker_secret(secret);
    }
    Ok(())
}

/// Tell the operator what was set. A generated deploy token is printed, with
/// the export every later deploy needs; no other value is printed.
fn report_worker_secret(secret: &WorkerSecret) {
    let name = secret.name;
    if !secret.generated {
        println!("-> set worker secret {name} (from env {name})");
        return;
    }
    println!("-> generated and set worker secret {name}");
    if name == impresspress_core::config_vars::DEPLOY_TOKEN_KEY {
        println!(
            "   IMPORTANT: export this for future `impresspress deploy` runs:\n     \
             export {name}={}\n   \
             It is printed here once. If this output is a CI log others can read, rotate it \
             (npx wrangler secret put {name} --name <worker_name>) and store the \
             new value as a CI secret; a first deploy with {name} already exported uses that \
             value and prints nothing.",
            secret.value
        );
    }
}

/// Create the main Worker as a placeholder and give it `secrets`, returning
/// the deploy token among them.
///
/// Checks again that the Worker is absent first: the build between
/// [`plan_main_worker`] and here takes minutes, and a Worker created in the
/// meantime must not have a placeholder deployed over it.
pub fn create_main_worker(
    commands: &impl WorkerCommands,
    placeholder_config: &Path,
    worker_name: &str,
    secrets: &[WorkerSecret],
) -> Result<String> {
    let token_key = impresspress_core::config_vars::DEPLOY_TOKEN_KEY;
    let deploy_token = secrets
        .iter()
        .find(|secret| secret.name == token_key)
        .map(|secret| secret.value.clone())
        .with_context(|| format!("no {token_key} among the secrets to set"))?;
    if commands.worker_exists(placeholder_config)? {
        bail!(
            "the Worker {worker_name} was absent when this deploy started and exists now; \
             nothing was deployed over it. Rerun `impresspress deploy` with {token_key} set to \
             the token that Worker was given."
        );
    }
    commands.deploy(placeholder_config)?;
    put_worker_secrets(commands, placeholder_config, secrets)?;
    Ok(deploy_token)
}

#[cfg(test)]
mod tests {
    use std::cell::RefCell;

    use super::*;

    const TOKEN: &str = "IMPRESSPRESS_DEPLOY_TOKEN";
    const JWT: &str = "WAFER_RUN__AUTH__JWT_SECRET";

    /// A [`WorkerCommands`] that records every call. `worker_exists` answers
    /// from a script while one is left, then from whether `deploy` has run;
    /// the secrets it holds are the ones `secret_put` set, and a put of
    /// `fail_put` fails.
    struct Recorder {
        exists: RefCell<Vec<Result<bool>>>,
        deployed: RefCell<bool>,
        held: RefCell<Vec<String>>,
        fail_put: Option<&'static str>,
        calls: RefCell<Vec<String>>,
    }

    impl Recorder {
        fn answering(exists: Vec<Result<bool>>) -> Self {
            Self {
                exists: RefCell::new(exists.into_iter().rev().collect()),
                deployed: RefCell::new(false),
                held: RefCell::new(Vec::new()),
                fail_put: None,
                calls: RefCell::new(Vec::new()),
            }
        }

        /// A Worker that exists and holds `held`.
        fn existing(held: &[&str]) -> Self {
            let recorder = Self::answering(Vec::new());
            *recorder.deployed.borrow_mut() = true;
            *recorder.held.borrow_mut() = held.iter().map(|name| name.to_string()).collect();
            recorder
        }

        fn calls(&self) -> Vec<String> {
            self.calls.take()
        }
    }

    impl WorkerCommands for Recorder {
        fn worker_exists(&self, config: &Path) -> Result<bool> {
            self.calls
                .borrow_mut()
                .push(format!("exists {}", config.display()));
            match self.exists.borrow_mut().pop() {
                Some(answer) => answer,
                None => Ok(*self.deployed.borrow()),
            }
        }

        fn deploy(&self, config: &Path) -> Result<()> {
            self.calls
                .borrow_mut()
                .push(format!("deploy {}", config.display()));
            *self.deployed.borrow_mut() = true;
            Ok(())
        }

        fn secret_put(&self, config: &Path, name: &str, value: &str) -> Result<()> {
            self.calls
                .borrow_mut()
                .push(format!("secret {name}={value} {}", config.display()));
            if self.fail_put == Some(name) {
                anyhow::bail!("wrangler secret put {name} failed");
            }
            self.held.borrow_mut().push(name.to_string());
            Ok(())
        }

        fn secret_names(&self, config: &Path) -> Result<Vec<String>> {
            self.calls
                .borrow_mut()
                .push(format!("list {}", config.display()));
            Ok(self.held.borrow().clone())
        }
    }

    fn secrets(token: &str) -> Vec<WorkerSecret> {
        vec![
            WorkerSecret {
                name: TOKEN,
                value: token.into(),
                generated: true,
            },
            WorkerSecret {
                name: JWT,
                value: "jwt".into(),
                generated: true,
            },
        ]
    }

    #[test]
    fn an_existing_worker_deploys_with_the_operators_token_and_creates_nothing() {
        let commands = Recorder::existing(&[TOKEN, JWT]);
        let plan = plan_main_worker(
            &commands,
            Path::new("p.toml"),
            "site",
            &secrets("new"),
            Some("tok".into()),
        )
        .unwrap();
        assert_eq!(
            plan,
            MainWorkerPlan::Existing {
                deploy_token: "tok".into()
            }
        );
        assert_eq!(commands.calls(), ["exists p.toml", "list p.toml"]);
    }

    /// Without the token an existing Worker that holds one cannot be
    /// prepared; the refusal names the one command that sets a new one, and
    /// nothing is set.
    #[test]
    fn an_existing_worker_without_a_token_is_refused_with_the_command_to_run() {
        for token in [None, Some(String::new())] {
            let commands = Recorder::existing(&[TOKEN, JWT]);
            let err = plan_main_worker(
                &commands,
                Path::new("p.toml"),
                "site",
                &secrets("new"),
                token,
            )
            .unwrap_err()
            .to_string();
            assert!(
                err.contains("npx wrangler secret put IMPRESSPRESS_DEPLOY_TOKEN --name site"),
                "{err}"
            );
            assert_eq!(commands.calls(), ["exists p.toml", "list p.toml"]);
        }
    }

    /// An absent Worker needs no token up front, whether or not one is set.
    #[test]
    fn an_absent_worker_is_planned_for_creation() {
        for token in [None, Some("tok".to_string())] {
            let commands = Recorder::answering(vec![Ok(false)]);
            assert_eq!(
                plan_main_worker(
                    &commands,
                    Path::new("p.toml"),
                    "site",
                    &secrets("new"),
                    token
                )
                .unwrap(),
                MainWorkerPlan::Create
            );
            assert_eq!(commands.calls(), ["exists p.toml"]);
        }
    }

    /// A check that failed for any other reason is not "absent": treating it
    /// as absent would deploy a placeholder over a live site.
    #[test]
    fn a_failed_existence_check_stops_the_deploy() {
        let commands = Recorder::answering(vec![Err(anyhow::anyhow!("not logged in"))]);
        let err = plan_main_worker(
            &commands,
            Path::new("p.toml"),
            "site",
            &secrets("new"),
            None,
        )
        .unwrap_err();
        assert!(err.to_string().contains("not logged in"), "{err}");
    }

    /// Creation deploys the placeholder, then sets the deploy token and the
    /// JWT secret on it, and hands back the token the rest of the deploy
    /// authenticates with.
    #[test]
    fn creation_deploys_the_placeholder_then_sets_both_secrets() {
        let commands = Recorder::answering(vec![Ok(false)]);
        let token =
            create_main_worker(&commands, Path::new("p.toml"), "site", &secrets("tok")).unwrap();
        assert_eq!(token, "tok");
        assert_eq!(
            commands.calls(),
            [
                "exists p.toml",
                "deploy p.toml",
                "secret IMPRESSPRESS_DEPLOY_TOKEN=tok p.toml",
                "secret WAFER_RUN__AUTH__JWT_SECRET=jwt p.toml",
            ]
        );
    }

    /// A first deploy that created the Worker and set its deploy token, then
    /// failed setting the JWT secret, is finished by the next run: the Worker
    /// exists, so the run lists its secret names, sets the JWT secret it
    /// lacks — and not the deploy token it holds — and then authenticates with
    /// the token the operator exported from the first run's output.
    #[test]
    fn a_rerun_after_a_failed_secret_write_sets_the_missing_secret() {
        let mut commands = Recorder::answering(vec![Ok(false)]);
        commands.fail_put = Some(JWT);
        let err = create_main_worker(&commands, Path::new("p.toml"), "site", &secrets("first"))
            .unwrap_err();
        assert!(err.to_string().contains(JWT), "{err}");
        assert_eq!(*commands.held.borrow(), [TOKEN]);
        commands.calls();
        commands.fail_put = None;

        let plan = plan_main_worker(
            &commands,
            Path::new("p.toml"),
            "site",
            &secrets("second"),
            Some("first".into()),
        )
        .unwrap();
        assert_eq!(
            plan,
            MainWorkerPlan::Existing {
                deploy_token: "first".into()
            }
        );
        assert_eq!(
            commands.calls(),
            [
                "exists p.toml",
                "list p.toml",
                "secret WAFER_RUN__AUTH__JWT_SECRET=jwt p.toml",
            ]
        );
    }

    /// A Worker that holds no deploy token (the first run stopped right after
    /// the placeholder deploy) is given one, and the deploy uses it without
    /// the operator having exported anything.
    #[test]
    fn a_worker_without_a_deploy_token_is_given_one_and_the_deploy_uses_it() {
        let commands = Recorder::existing(&[]);
        let plan = plan_main_worker(
            &commands,
            Path::new("p.toml"),
            "site",
            &secrets("new"),
            None,
        )
        .unwrap();
        assert_eq!(
            plan,
            MainWorkerPlan::Existing {
                deploy_token: "new".into()
            }
        );
        assert_eq!(
            commands.calls(),
            [
                "exists p.toml",
                "list p.toml",
                "secret IMPRESSPRESS_DEPLOY_TOKEN=new p.toml",
                "secret WAFER_RUN__AUTH__JWT_SECRET=jwt p.toml",
            ]
        );
    }

    /// A Worker that appeared while the deploy was building is left alone.
    #[test]
    fn a_worker_created_meanwhile_is_never_deployed_over() {
        let commands = Recorder::answering(vec![Ok(true)]);
        let err = create_main_worker(&commands, Path::new("p.toml"), "site", &secrets("tok"))
            .unwrap_err()
            .to_string();
        assert!(err.contains("nothing was deployed over it"), "{err}");
        assert_eq!(commands.calls(), ["exists p.toml"]);
    }

    #[test]
    fn secrets_come_from_the_environment_when_set_and_are_minted_otherwise() {
        let secrets = resolve_worker_secrets(
            |name| (name == TOKEN).then(|| "from-env".to_string()),
            || Ok([0xab; 32]),
        )
        .unwrap();
        assert_eq!(
            secrets,
            [
                WorkerSecret {
                    name: TOKEN,
                    value: "from-env".into(),
                    generated: false,
                },
                WorkerSecret {
                    name: JWT,
                    value: "ab".repeat(32),
                    generated: true,
                },
            ]
        );
    }
}
