//! wrangler.toml generation + override merging.
//!
//! [`CloudflareConfig`] is the *resolved* shape consumed by [`generate`].
//! Parsing impresspress.toml + applying env-var overlays lives in
//! [`super::env`], which produces this type.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use super::build::WORKER_BUILD_VERSION;

#[derive(Debug, Clone)]
pub struct CloudflareConfig {
    pub account_id: String,
    pub worker_name: String,
    pub compatibility_date: String,
    pub d1: D1Config,
    pub r2: R2Config,
    /// Path (relative to consumer repo root) to a TOML file whose contents
    /// are deep-merged over the generated defaults. None means "no overrides."
    pub wrangler_overrides_path: Option<PathBuf>,
    /// Workers Observability head sampling rate (`0.0..=1.0`), resolved by
    /// [`super::env::RawCloudflareConfig::resolve`] from
    /// `IMPRESSPRESS_CLOUDFLARE_HEAD_SAMPLING_RATE` / `impresspress.toml`'s
    /// `[cloudflare].head_sampling_rate`, defaulting to `1.0` (100%) when
    /// neither is set. Explicit and configurable rather than hardcoded, so a
    /// deployment that outgrows 100%-capture traffic doesn't have to reach
    /// for a `wrangler_overrides_path` file to dial it down.
    pub head_sampling_rate: f64,
}

#[derive(Debug, Clone)]
pub struct D1Config {
    pub binding: String,
    pub database_name: String,
    pub database_id: String,
}

#[derive(Debug, Clone)]
pub struct R2Config {
    pub binding: String,
    pub bucket_name: String,
}

pub fn generate(cfg: &CloudflareConfig, repo_root: &Path, out_dir: &Path) -> Result<PathBuf> {
    let mut value = base_toml(cfg);

    if let Some(rel) = cfg.wrangler_overrides_path.as_ref() {
        let abs = repo_root.join(rel);
        let raw = std::fs::read_to_string(&abs)
            .with_context(|| format!("read overrides {}", abs.display()))?;
        let overrides: toml::Value =
            toml::from_str(&raw).with_context(|| format!("parse overrides {}", abs.display()))?;
        deep_merge(&mut value, overrides);
    }

    let body = toml::to_string_pretty(&value).context("serialize wrangler.toml")?;
    let header = "# Generated by `impresspress build --target cloudflare`. \
                  Do not edit. Regenerated each build.\n\n";
    let path = out_dir.join("wrangler.toml");
    std::fs::write(&path, format!("{header}{body}"))
        .with_context(|| format!("write {}", path.display()))?;
    Ok(path)
}

fn base_toml(cfg: &CloudflareConfig) -> toml::Value {
    use toml::Value;

    let mut root = toml::map::Map::new();
    root.insert("name".into(), Value::String(cfg.worker_name.clone()));
    root.insert(
        "main".into(),
        Value::String("../../build/worker/shim.mjs".into()),
    );
    root.insert(
        "compatibility_date".into(),
        Value::String(cfg.compatibility_date.clone()),
    );
    // Required so `wrangler versions upload` prints a "Version Preview
    // URL" line — `impresspress deploy` parses that URL to call the new
    // version's own `/_deploy/init` before promoting it.
    root.insert("preview_urls".into(), Value::Boolean(true));

    let mut build = toml::map::Map::new();
    // Pinned to an exact version (`WORKER_BUILD_VERSION`, shared with the
    // local `impresspress build --target cloudflare` path in
    // `build::ensure_worker_build_installed`) — worker-build 0.8.x rejects
    // consumers using `worker < 0.8` (hard version check) and changed its
    // output layout from `build/worker/shim.mjs` (which `main` points to)
    // to `build/index.js`. Until we upgrade the `worker` crate, lock the
    // toolchain to this exact version for both the local build and the
    // wrangler-driven rebuild during deploy.
    //
    // The `command -v ... && [ ... ] ||` guard skips `cargo install`
    // outright when the pinned version is already on `PATH` (e.g. a build
    // environment that persists `~/.cargo/bin` across runs), instead of
    // reinstalling unconditionally on every build.
    build.insert(
        "command".into(),
        Value::String(format!(
            "((command -v worker-build >/dev/null 2>&1 && \
             [ \"$(worker-build --version)\" = \"{WORKER_BUILD_VERSION}\" ]) || \
             cargo install worker-build --version \"={WORKER_BUILD_VERSION}\" --quiet) && \
             worker-build --release --no-default-features \
             --features target-cloudflare"
        )),
    );
    root.insert("build".into(), Value::Table(build));

    let mut d1_entry = toml::map::Map::new();
    d1_entry.insert("binding".into(), Value::String(cfg.d1.binding.clone()));
    d1_entry.insert(
        "database_name".into(),
        Value::String(cfg.d1.database_name.clone()),
    );
    d1_entry.insert(
        "database_id".into(),
        Value::String(cfg.d1.database_id.clone()),
    );
    root.insert(
        "d1_databases".into(),
        Value::Array(vec![Value::Table(d1_entry)]),
    );

    let mut r2_entry = toml::map::Map::new();
    r2_entry.insert("binding".into(), Value::String(cfg.r2.binding.clone()));
    r2_entry.insert(
        "bucket_name".into(),
        Value::String(cfg.r2.bucket_name.clone()),
    );
    root.insert(
        "r2_buckets".into(),
        Value::Array(vec![Value::Table(r2_entry)]),
    );

    // Plain worker vars (`env.var(...)`), read at runtime by the CF adapter.
    // STRICT_SCHEMA on: the D1 database service trusts its migrated schema and
    // skips the per-op table-exists probe + lazy ADD COLUMN, removing a network
    // round-trip per logical op on D1. This is a deploy-time operational
    // decision (not an admin-editable runtime toggle), so it lives here rather
    // than in the D1 `variables` table. The adapter's `build_runtime` threads
    // this into the config snapshot so the `wafer-run/database` block applies
    // it at Init. A consumer that needs the self-healing lazy-schema behavior
    // can flip it back off via `wrangler_overrides_path`.
    let mut vars = toml::map::Map::new();
    vars.insert(
        wafer_core::interfaces::database::handler::STRICT_SCHEMA_CONFIG_KEY.into(),
        Value::String("true".into()),
    );
    root.insert("vars".into(), Value::Table(vars));

    // Workers Logs (a.k.a. Workers Observability). Off by default at the
    // platform; we turn it on so dashboard logs + the `wrangler tail`
    // request envelope are populated. `head_sampling_rate` is an explicit,
    // configurable knob (`cfg.head_sampling_rate`, see
    // `CloudflareConfig::head_sampling_rate`) rather than hardcoded — set
    // `[cloudflare].head_sampling_rate` in impresspress.toml or
    // `IMPRESSPRESS_CLOUDFLARE_HEAD_SAMPLING_RATE` for a deployment whose
    // traffic has outgrown 100% capture.
    let mut obs = toml::map::Map::new();
    obs.insert("enabled".into(), Value::Boolean(true));
    obs.insert(
        "head_sampling_rate".into(),
        Value::Float(cfg.head_sampling_rate),
    );
    root.insert("observability".into(), Value::Table(obs));

    Value::Table(root)
}

/// Deep-merge `overrides` into `base`. Tables merge recursively;
/// arrays and primitives are replaced wholesale.
fn deep_merge(base: &mut toml::Value, overrides: toml::Value) {
    use toml::Value;
    match (base, overrides) {
        (Value::Table(b), Value::Table(o)) => {
            for (k, v) in o {
                match b.get_mut(&k) {
                    Some(existing) => deep_merge(existing, v),
                    None => {
                        b.insert(k, v);
                    }
                }
            }
        }
        (slot, replacement) => *slot = replacement,
    }
}
