import { test, expect, type Page } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { loginToWorkspace } from './fixtures/dev-sandbox';
import { pinnedToolchainEnv } from './fixtures/rust-toolchain';
import { execute, waitForTool, type ToolResult } from './fixtures/webmcp-helpers';

/**
 * `dev_compile_block` — the tool that turns Rust in the workspace into a
 * block serving at `/b/<name>/`.
 *
 * Everything below the tool is already covered elsewhere:
 * `dev-compiler.spec.ts` drives `BrowserRustCompiler` against the protocol and
 * proves the packaged worker is allowed to start at all, and
 * `dev-foundations.spec.ts` drives `POST /b/dev/api/builds/stage` with a
 * pre-built guest over `fetch`. What is left — and what is here — is the page
 * function that joins them: read `blocks/<name>/` out of the workspace, hand
 * it to the compiler, base64 the module it produced, stage it, and report the
 * result to whoever asked, whether that was an agent or the Compile button.
 *
 * # Why the worker is a fake and the artifact is not
 *
 * The real toolchain is 72 MiB and takes ~38 s to build the `hello` template
 * (`compiler/README.md`), which is Plan 3 Task 6's bill to pay, not this
 * file's. But the sixteen bytes `fixtures/fake-compiler-worker.js` normally
 * answers with would stop this test at the first thing it wants to prove:
 * staging INSTANTIATES the module, reads its `BlockInfo` and runs its
 * lifecycle before it will activate anything, so sixteen bytes are refused and
 * `/b/hello/` never exists.
 *
 * So the artifact is real and the compiler is not. The test scaffolds the
 * block through `dev_create_block`, reads its two files back out of the
 * workspace through `dev_read_file`, lays them beside the guest SDK crate
 * `GET /b/dev/api/guest` serves (the one the real compiler session is started
 * with), builds THOSE BYTES on the host with
 * `cargo build --release --target wasm32-wasip1`, and drops the module beside
 * the fake worker, which serves it as its own output. Everything the tool does
 * with that module — the base64, the source digest, the guest version, the
 * staging call, the validation, the runtime rebuild, the route that appears —
 * is the real thing running against a real `wasm32-wasip1` guest.
 *
 * # How the page is pointed at it
 *
 * `dev.js` reads one fixed URL for the compiler manifest
 * (`/__impresspress_dev/compiler/manifest.json`) and that is deliberate: which
 * toolchain a build carries is a property of the BUNDLE's asset overlay, not a
 * setting a page may be talked out of. So there is no override to reach for,
 * and the only honest way to hand the page a different toolchain is to change
 * what that URL answers. This spec therefore swaps the served manifest for one
 * naming the fake worker and puts the original bytes back afterwards. It is
 * safe because `playwright.config.ts` runs ONE worker with `fullyParallel:
 * false` — no other spec can be looking at that file while this one runs — and
 * because `dist/` is build output, regenerated by `build.sh`.
 */

/**
 * The bundle being served on `TEST_PORT`.
 *
 * CI exports `DEV_DIST` from `build.sh`'s last line; a local run defaults to
 * the same path that script writes to.
 */
const DEV_DIST =
  process.env.DEV_DIST ??
  fileURLToPath(new URL('../../../../examples/dev-sandbox/dist', import.meta.url));

/**
 * The fixture's own directory, deliberately NOT the `test/` one
 * `dev-compiler.spec.ts` uses: a real `hello.wasm` next to that worker would
 * change what its protocol assertions see (they pin the canned sixteen
 * bytes), and two specs sharing a directory would couple them through the
 * order they happen to run in.
 */
const TOOL_COMPILER_DIR = path.join(DEV_DIST, '__impresspress_dev', 'compiler', 'tool');
const TOOL_WORKER_URL = '/__impresspress_dev/compiler/tool/worker.js';

const FAKE_WORKER = fileURLToPath(new URL('./fixtures/fake-compiler-worker.js', import.meta.url));

/** The manifest `dev.js` reads, and the bytes `build.sh` put there. */
const REAL_MANIFEST_FILE = path.join(DEV_DIST, '__impresspress_dev', 'compiler', 'manifest.json');
let realManifest: Buffer;

/** What `fake-compiler-worker.js` answers `rustc --version` with. */
const FAKE_RUSTC_VERSION = 'rustc 1.90.0-nightly (fake worker)';

/** The block the test builds, and the one the `hello` template is written for. */
const BLOCK = 'hello';

/**
 * The block whose name makes the fake worker break its own protocol.
 *
 * `crateName` is the fake's only switch (it is the one field of a compile
 * message the page controls), and the block-name rule — lowercase letters,
 * digits and hyphens — admits this one, so a real scaffolded block can carry
 * it. Compiling it is how the adapter's "destroy the worker and reject" path
 * is reached through the TOOL rather than through the adapter's own API.
 */
const BROKEN = 'protocol-error';

/** What the `hello` template's one endpoint answers with, verbatim. */
const GREETING = 'Hello from site/hello — a block compiled in your browser.';

/** What it answers with once step 5 has given it an agent tool. */
const GREETING_WITH_TOOL = 'Hello from site/hello — now with an agent tool.';

/** …and after the one-literal edit step 5 recompiles. */
const GREETING_EDITED = 'Hello from site/hello — edited, recompiled, same tool.';

/** The block's source file every edit below goes through. */
const LIB_RS = `blocks/${BLOCK}/src/lib.rs`;

/**
 * The two files `dev_create_block` scaffolds, in the order it reports them.
 * The SDK is not among them: `Cargo.toml` reaches it by path
 * (`../../wafer_guest`), and the compiler session supplies that crate.
 */
const CRATE_FILES = [`blocks/${BLOCK}/Cargo.toml`, LIB_RS];

test.beforeAll(() => {
  mkdirSync(TOOL_COMPILER_DIR, { recursive: true });
  copyFileSync(FAKE_WORKER, path.join(TOOL_COMPILER_DIR, 'worker.js'));

  if (!existsSync(REAL_MANIFEST_FILE)) {
    throw new Error(
      `${REAL_MANIFEST_FILE} is missing: this bundle was built without the compiler overlay, ` +
        'so `/b/dev` would report "No compiler in this build" and nothing here could run. ' +
        'Rebuild with examples/dev-sandbox/build.sh.',
    );
  }
  realManifest = readFileSync(REAL_MANIFEST_FILE);
  // The same shape `scripts/write-manifest.mjs` writes, minus the asset
  // inventory nothing on the page reads: the adapter takes `entry`, `version`
  // and `target`, and refuses a manifest missing any of them.
  writeFileSync(
    REAL_MANIFEST_FILE,
    `${JSON.stringify(
      {
        schema_version: 1,
        version: 'test',
        entry: TOOL_WORKER_URL,
        total_bytes: 0,
        assets: [],
        license: 'MIT OR Apache-2.0',
        target: 'wasm32-wasip1',
      },
      null,
      2,
    )}\n`,
  );
});

test.afterAll(() => {
  // Byte for byte what `build.sh` produced. The fixture must not outlive the
  // run that needed it — least of all in a tree a deploy uploads.
  writeFileSync(REAL_MANIFEST_FILE, realManifest);
  rmSync(TOOL_COMPILER_DIR, { recursive: true, force: true });
});

/** The structured half of a tool result, with "and it was not an error" folded in. */
function structured<T>(result: ToolResult): T {
  expect(result.isError, result.content[0]?.text).toBeFalsy();
  expect(result.structuredContent, JSON.stringify(result)).toBeTruthy();
  return result.structuredContent as unknown as T;
}

type FileEntry = { path: string; sha256: string; size: number };
type FileRead = FileEntry & { encoding: string; content: string };
type CreateBlock = { name: string; files: FileEntry[] };
type Generation = { id: string; cause: string; status: string };
type Diagnostic = { severity: string; code: string; message: string; file: string | null };
type Compile = {
  success: boolean;
  build_id: string | null;
  generation: Generation | null;
  diagnostics: Diagnostic[];
  stdout: string;
  stderr: string;
  elapsed_ms: number;
  compiler_version: string | null;
  progress: Array<{ phase: string; ms: number }>;
};

/**
 * Build the workspace's CURRENT `blocks/<BLOCK>/` on the host, and drop the
 * module where the fake worker serves its output from.
 *
 * Read back through `dev_read_file` — the tool an agent would use — and not
 * off the host's copy of the templates: what gets compiled has to be what the
 * WORKSPACE holds, or this proves nothing about the round trip the sandbox
 * actually makes. Which also makes it the way an edit reaches the artifact:
 * write the file through the tool, call this, compile.
 *
 * The guest SDK comes from `GET /b/dev/api/guest` — the crate the real worker
 * builds once per session — and goes where the block's
 * `wafer_guest = { path = "../../wafer_guest" }` looks for it: the same
 * `<root>/wafer_guest/` beside `<root>/blocks/<BLOCK>/` layout the worker
 * writes, so a template whose path drifted from the served crate fails here.
 *
 * `--offline` because a sandbox block and its guest crate have no registry
 * dependencies by construction (the browser toolchain has no registry access)
 * — a build that needed the network here would mean the template or the SDK
 * had grown a dependency it cannot have.
 */
async function buildOnHost(page: Page, files: string[]) {
  const root = mkdtempSync(path.join(tmpdir(), 'dev-compile-'));
  // Removed however the build ends: a failed fetch, read or cargo run must
  // not leave a temp crate and its target dir behind.
  try {
    const guest = await page.evaluate(() =>
      fetch('/b/dev/api/guest').then((r) => r.json() as Promise<{ files: Record<string, string> }>),
    );
    for (const [rel, content] of Object.entries(guest.files)) {
      const target = path.join(root, 'wafer_guest', rel);
      mkdirSync(path.dirname(target), { recursive: true });
      writeFileSync(target, content);
    }
    const crate = path.join(root, 'blocks', BLOCK);
    for (const entryPath of files) {
      const file = structured<FileRead>(await execute(page, 'dev_read_file', { path: entryPath }));
      expect(file.encoding).toBe('utf8');
      const target = path.join(crate, entryPath.slice(`blocks/${BLOCK}/`.length));
      mkdirSync(path.dirname(target), { recursive: true });
      writeFileSync(target, file.content);
    }
    const targetDir = path.join(root, 'target');
    execFileSync(
      'cargo',
      ['build', '--release', '--target', 'wasm32-wasip1', '--offline', '--target-dir', targetDir],
      // `crate` is under the system temp directory, where no
      // `rust-toolchain.toml` is in scope: name the pinned toolchain.
      { cwd: crate, stdio: 'inherit', env: pinnedToolchainEnv() },
    );
    copyFileSync(
      path.join(targetDir, 'wasm32-wasip1', 'release', `${BLOCK}.wasm`),
      path.join(TOOL_COMPILER_DIR, `${BLOCK}.wasm`),
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

/**
 * Replace `blocks/<BLOCK>/src/lib.rs` with `edit(current)`, through the tool
 * (so the compare-and-swap on the digest is the real one), and rebuild the
 * host artifact from it.
 */
async function editAndBuild(page: Page, edit: (source: string) => string) {
  const current = structured<FileRead>(await execute(page, 'dev_read_file', { path: LIB_RS }));
  const content = edit(current.content);
  expect(content, 'the edit matched nothing — the hello template has drifted').not.toBe(
    current.content,
  );
  structured(
    await execute(page, 'dev_write_file', {
      path: LIB_RS,
      content,
      expected_sha256: current.sha256,
    }),
  );
  await buildOnHost(page, CRATE_FILES);
}

/** What `GET /b/<name>/` answers right now, read from inside the document. */
async function fetchBlock(page: Page, name: string) {
  return page.evaluate(async (blockName) => {
    const response = await fetch(`/b/${blockName}/`);
    return { status: response.status, body: await response.text() };
  }, name);
}

test('dev_compile_block compiles a scaffolded block, stages it and puts it live; failures are results', async ({
  page,
}) => {
  // A cold boot compiles the wasm, creates the OPFS database, runs every
  // block's migrations and imports the seed; three activations then each
  // rebuild the wasmi runtime. The default 60 s is a boot budget.
  test.setTimeout(900_000);

  await loginToWorkspace(page);
  await waitForTool(page, 'dev_create_block');
  await waitForTool(page, 'dev_compile_block');

  // The page found the (substituted) manifest: the version line is written,
  // and the only thing still holding the button back is that the workspace has
  // no blocks yet. Without this the tool below would refuse with "No compiler
  // in this build." and every assertion after it would be about the wrong
  // thing.
  await expect(page.locator('#dev-compiler-version')).toHaveText(/^Compiler vtest /);
  await expect(page.locator('#dev-compile')).toBeDisabled();

  // --- 1. Scaffold, and build the very same bytes on the host -------------
  const created = structured<CreateBlock>(
    await execute(page, 'dev_create_block', { name: BLOCK, template: 'hello' }),
  );
  // …and now there is something to compile, so the button turns on. Both
  // halves of `updateCompileButton`, in the order a first-time visitor meets
  // them.
  await expect(page.locator('#dev-compile')).toBeEnabled();
  expect(created.files.map((f) => f.path)).toEqual(CRATE_FILES);
  await buildOnHost(page, CRATE_FILES);

  // --- 2. Compile: the block is validated and live when the call returns ---
  const built = structured<Compile>(await execute(page, 'dev_compile_block', { name: BLOCK }));
  expect(built.success).toBe(true);
  expect(built.diagnostics).toEqual([]);
  expect(built.build_id).toBeTruthy();
  // `GenerationCause::BlockCompile`, in its serde spelling: the block set
  // changed, so this generation is not a site write.
  expect(built.generation?.cause).toBe('block_compile');
  expect(built.generation?.status).toBe('active');
  // `rustc --version` as the worker reported it at `ready` — the string the
  // build row records as `compiler_version`, not one the page made up.
  expect(built.compiler_version).toBe(FAKE_RUSTC_VERSION);
  // Every phase of `ActivationPhase`, in order: a new block means the runtime
  // was rebuilt, which is the step a site-only write skips.
  expect(built.progress.map((p) => p.phase)).toEqual([
    'validating',
    'building_runtime',
    'publishing',
    'active',
  ]);

  // The panel shows the activation that just landed, and still shows it after
  // the catch-up poll `withProgress` runs on the way out — the journal has
  // rested at `idle` by then, so a ladder drawn from the status alone would
  // have blanked here.
  await expect(page.locator('#dev-progress-steps')).toHaveAttribute('data-phase', 'active');
  await expect(page.locator('#dev-progress-steps li[data-state="done"]')).toHaveCount(4);
  await expect(page.locator('#dev-log')).toContainText(`compiled ${BLOCK} — generation`);

  // …and the route is live. This is the whole claim: Rust written in a
  // browser, compiled, validated and serving, without a server anywhere.
  expect(await fetchBlock(page, BLOCK)).toEqual({ status: 200, body: GREETING });

  // --- 3. An adapter that broke leaves a page that still compiles ---------
  //
  // The fake worker answers this crate with an out-of-band `error`, which the
  // adapter treats as "nothing this worker says can be trusted": it terminates
  // it and rejects. That is NOT a verdict on the block, so it reaches the
  // agent as `isError` rather than as a failed build.
  structured<CreateBlock>(await execute(page, 'dev_create_block', { name: BROKEN, template: 'hello' }));
  const broke = await execute(page, 'dev_compile_block', { name: BROKEN });
  expect(broke.isError).toBe(true);
  expect(broke.content[0].text).toContain('the compiler image is corrupt');
  expect(broke.structuredContent).toBeUndefined();
  // The previous generation is untouched by a compiler that fell over.
  expect((await fetchBlock(page, BLOCK)).status).toBe(200);

  // --- 4. The Compile button runs the same function, on a fresh worker -----
  //
  // Nothing re-initialises the compiler between the violation above and this
  // click: the adapter builds a new worker on demand, and the button is how a
  // human would find that out. It also exercises the select — populated from
  // the `blocks/<name>/` prefixes in the file listing, which now has two.
  await expect(page.locator('#dev-compile-block option')).toHaveCount(2);
  await page.locator('#dev-compile-block').selectOption(BLOCK);
  // A NEW generation is the proof, not a log line: the panel already carries
  // one from step 2, so `#dev-log` alone would be satisfied by a button that
  // did nothing at all. Read without `structured`, because a poll's callback
  // must return a value rather than raise its own assertions.
  const activeGeneration = async () => {
    const result = await execute(page, 'dev_status', {});
    return (result.structuredContent as { active_generation: Generation | null })?.active_generation
      ?.id;
  };
  const before = await activeGeneration();
  expect(before).toBeTruthy();
  await page.locator('#dev-compile').click();
  await expect.poll(activeGeneration, { timeout: 120_000 }).not.toBe(before);
  expect(await fetchBlock(page, BLOCK)).toEqual({ status: 200, body: GREETING });

  // --- 5. Recompiling a block that declares an agent tool -----------------
  //
  // The case a browser agent hit and nothing here covered. Every compile above
  // is either a block's FIRST, or a recompile of a block with no agent tool —
  // and the duplicate-tool-name rule has nothing to say about a block that
  // declares none, so `site/hello` as the template ships it could never
  // exercise it. Staging seeded "already claimed" from the runtime's
  // registered blocks, which after the rebuild in step 2 INCLUDE the live
  // `site/hello`, so the second compile of a block with a tool was refused
  // `tool-name-duplicate` naming a tool only that block had ever declared. The
  // agent's only way forward was `dev_remove_block` and a compile from
  // nothing, with the block offline in between.
  //
  // First give it a tool, which is itself a compile of a NEW declaration…
  await editAndBuild(page, (source) =>
    source
      .replace(
        '.summary("Say hello"),',
        '.summary("Say hello")\n            .agent_tool("hello_tool", "Says hello."),',
      )
      .replace(`"${GREETING}"`, `"${GREETING_WITH_TOOL}"`),
  );
  const tooled = structured<Compile>(await execute(page, 'dev_compile_block', { name: BLOCK }));
  expect(tooled.success, JSON.stringify(tooled.diagnostics)).toBe(true);
  expect(await fetchBlock(page, BLOCK)).toEqual({ status: 200, body: GREETING_WITH_TOOL });

  // …and now the recompile itself: the same block, the same tool, one string
  // literal changed — the smallest edit a developer makes, and the one that
  // used to take the block down.
  await editAndBuild(page, (source) =>
    source.replace(`"${GREETING_WITH_TOOL}"`, `"${GREETING_EDITED}"`),
  );
  const recompiled = structured<Compile>(await execute(page, 'dev_compile_block', { name: BLOCK }));
  expect(recompiled.success, JSON.stringify(recompiled.diagnostics)).toBe(true);
  expect(recompiled.diagnostics).toEqual([]);
  // A new generation, active, and the block still one of one: a recompile
  // REPLACES the block rather than joining the set beside itself.
  expect(recompiled.generation?.status).toBe('active');
  expect(recompiled.generation?.id).not.toBe(tooled.generation?.id);
  expect(await fetchBlock(page, BLOCK)).toEqual({ status: 200, body: GREETING_EDITED });

  // --- 6. A crate that does not compile is an ANSWER ----------------------
  const source = structured<FileRead>(await execute(page, 'dev_read_file', { path: LIB_RS }));
  structured(
    await execute(page, 'dev_write_file', {
      path: LIB_RS,
      content: `${source.content}\nFAIL`,
      expected_sha256: source.sha256,
    }),
  );
  const failed = structured<Compile>(await execute(page, 'dev_compile_block', { name: BLOCK }));
  expect(failed.success).toBe(false);
  // No build row and no generation: nothing was staged, because nothing
  // compiled.
  expect(failed.build_id).toBeNull();
  expect(failed.generation).toBeNull();
  expect(failed.diagnostics[0]).toMatchObject({ file: 'src/lib.rs', severity: 'error' });
  // …and the block that WAS compiled is still serving. A failed compile is not
  // a deployment.
  expect(await fetchBlock(page, BLOCK)).toEqual({ status: 200, body: GREETING_EDITED });
});
